services:
  - type: web
    name: aspirantes-utem-prueba
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

